# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdec.proto\x12\x08grpc_dec\"%\n\x06Logits\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"W\n\rTranscription\x12\x14\n\x0cgreedy_trans\x18\x01 \x01(\t\x12\x12\n\nbeam_trans\x18\x02 \x01(\t\x12\x1c\n\x14\x62\x65\x61m_decoded_offsets\x18\x03 \x03(\x05\x32@\n\x07\x44\x65\x63oder\x12\x35\n\x06\x44\x65\x63ode\x12\x10.grpc_dec.Logits\x1a\x17.grpc_dec.Transcription\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGITS._serialized_start=23
  _LOGITS._serialized_end=60
  _TRANSCRIPTION._serialized_start=62
  _TRANSCRIPTION._serialized_end=149
  _DECODER._serialized_start=151
  _DECODER._serialized_end=215
# @@protoc_insertion_point(module_scope)
