# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dec_pb2 as dec__pb2


class DecoderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decode = channel.unary_unary(
                '/grpc_dec.Decoder/Decode',
                request_serializer=dec__pb2.Logits.SerializeToString,
                response_deserializer=dec__pb2.Transcription.FromString,
                )


class DecoderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=dec__pb2.Logits.FromString,
                    response_serializer=dec__pb2.Transcription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_dec.Decoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Decoder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_dec.Decoder/Decode',
            dec__pb2.Logits.SerializeToString,
            dec__pb2.Transcription.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
